# Generated by Django 3.0.3 on 2020-02-19 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200219_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
