# Generated by Django 3.0.3 on 2020-02-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200215_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='car_make',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='car_model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='car_plate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
