# Generated by Django 3.0.3 on 2020-02-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_jobpost_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequestPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(help_text='Optional', max_length=254)),
                ('pickup_date', models.DateField()),
                ('interview_duration', models.CharField(max_length=30)),
                ('pickup_address', models.CharField(max_length=200)),
                ('interview_address', models.CharField(max_length=200)),
            ],
        ),
    ]
