# Generated by Django 3.0.3 on 2020-02-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200221_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequestpost',
            name='email',
        ),
        migrations.RemoveField(
            model_name='riderequestpost',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='riderequestpost',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='riderequestpost',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='riderequestpost',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='riderequestpost',
            name='pickup_time',
            field=models.CharField(default='0:00', max_length=20),
        ),
    ]
